"""Domain objects for DoomDeck launch presets and manifests."""
from __future__ import annotations

import dataclasses
from collections.abc import Mapping as MappingType
from pathlib import Path
from typing import Mapping

from doomdeck.domain.models import DoomDeckError

PRESET_MANIFEST_SCHEMA = "doom-deck-setup/preset-manifest/v1"
PRESET_MANIFEST_WARNING = (
    "This is a stable manifest generated by DoomDeck. Doom Runner options.json copies are generated separately."
)


def _required_text(value: str, label: str) -> str:
    text = str(value).strip()
    if not text:
        raise DoomDeckError(f"{label} must not be empty")
    return text


def _required_path(value: str | Path, label: str) -> Path:
    text = str(value).strip()
    if not text:
        raise DoomDeckError(f"{label} must not be empty")
    return Path(text)


def _json_object(value: object, label: str) -> Mapping[str, object]:
    if not isinstance(value, MappingType):
        raise DoomDeckError(f"{label} must be an object")
    return {str(key): item for key, item in value.items()}


def _json_text(value: object, label: str) -> str:
    if not isinstance(value, str):
        raise DoomDeckError(f"{label} must be text")
    return _required_text(value, label)


def _optional_json_text(data: Mapping[str, object], key: str, label: str) -> str:
    if key not in data:
        return ""
    value = data[key]
    if value is None:
        return ""
    if not isinstance(value, str):
        raise DoomDeckError(f"{label} must be text")
    return value


def _json_path(value: object, label: str) -> Path:
    if not isinstance(value, str):
        raise DoomDeckError(f"{label} must be text")
    return _required_path(value, label)


def _required_value(data: Mapping[str, object], key: str, label: str) -> object:
    if key not in data:
        raise DoomDeckError(f"{label} is missing")
    return data[key]


@dataclasses.dataclass(frozen=True)
class EngineSpec:
    name: str
    executable: Path
    family: str
    config_directory: Path
    data_directory: Path

    def __post_init__(self) -> None:
        object.__setattr__(self, "name", _required_text(self.name, "Engine name"))
        object.__setattr__(self, "family", _required_text(self.family, "Engine family"))
        object.__setattr__(self, "executable", _required_path(self.executable, "Engine executable"))
        object.__setattr__(self, "config_directory", _required_path(self.config_directory, "Engine config directory"))
        object.__setattr__(self, "data_directory", _required_path(self.data_directory, "Engine data directory"))

    def as_json_object(self) -> dict[str, str]:
        return {
            "name": self.name,
            "executable": str(self.executable),
            "family": self.family,
            "config_directory": str(self.config_directory),
            "data_directory": str(self.data_directory),
        }

    @classmethod
    def from_json_object(cls, value: object) -> "EngineSpec":
        data = _json_object(value, "Engine spec")
        return cls(
            name=_json_text(_required_value(data, "name", "Engine name"), "Engine name"),
            executable=_json_path(_required_value(data, "executable", "Engine executable"), "Engine executable"),
            family=_json_text(_required_value(data, "family", "Engine family"), "Engine family"),
            config_directory=_json_path(
                _required_value(data, "config_directory", "Engine config directory"),
                "Engine config directory",
            ),
            data_directory=_json_path(_required_value(data, "data_directory", "Engine data directory"), "Engine data directory"),
        )


@dataclasses.dataclass(frozen=True)
class Preset:
    name: str
    category: str
    engine: str
    iwad: Path
    config: Path
    autoexec: Path
    launcher: Path
    files: tuple[Path, ...] = ()
    missing_hint: str = ""
    notes: str = ""
    steam_shortcut_name: str = ""
    launch_options: str = ""

    def __post_init__(self) -> None:
        object.__setattr__(self, "name", _required_text(self.name, "Preset name"))
        object.__setattr__(self, "category", _required_text(self.category, "Preset category"))
        object.__setattr__(self, "engine", _required_text(self.engine, "Preset engine"))
        object.__setattr__(self, "iwad", _required_path(self.iwad, "Preset IWAD"))
        object.__setattr__(self, "config", _required_path(self.config, "Preset config"))
        object.__setattr__(self, "autoexec", _required_path(self.autoexec, "Preset autoexec"))
        object.__setattr__(self, "launcher", _required_path(self.launcher, "Preset launcher"))
        object.__setattr__(self, "files", tuple(_required_path(file_path, "Preset file") for file_path in self.files))

    def with_launch_metadata(self, steam_shortcut_name: str, launch_options: str) -> "Preset":
        return dataclasses.replace(
            self,
            steam_shortcut_name=_required_text(steam_shortcut_name, "Steam shortcut name"),
            launch_options=str(launch_options),
        )

    def as_json_object(self) -> dict[str, object]:
        data: dict[str, object] = {
            "name": self.name,
            "category": self.category,
            "engine": self.engine,
            "iwad": str(self.iwad),
            "files": [str(file_path) for file_path in self.files],
            "config": str(self.config),
            "autoexec": str(self.autoexec),
            "launcher": str(self.launcher),
        }
        if self.missing_hint:
            data["missing_hint"] = self.missing_hint
        if self.notes:
            data["notes"] = self.notes
        if self.steam_shortcut_name:
            data["steam_shortcut_name"] = self.steam_shortcut_name
        if self.launch_options:
            data["launch_options"] = self.launch_options
        return data

    @classmethod
    def from_json_object(cls, value: object) -> "Preset":
        data = _json_object(value, "Preset")
        files_value = data.get("files", [])
        if not isinstance(files_value, list):
            raise DoomDeckError("Preset files must be a list")
        return cls(
            name=_json_text(_required_value(data, "name", "Preset name"), "Preset name"),
            category=_json_text(_required_value(data, "category", "Preset category"), "Preset category"),
            engine=_json_text(_required_value(data, "engine", "Preset engine"), "Preset engine"),
            iwad=_json_path(_required_value(data, "iwad", "Preset IWAD"), "Preset IWAD"),
            files=tuple(_json_path(file_path, "Preset file") for file_path in files_value),
            config=_json_path(_required_value(data, "config", "Preset config"), "Preset config"),
            autoexec=_json_path(_required_value(data, "autoexec", "Preset autoexec"), "Preset autoexec"),
            launcher=_json_path(_required_value(data, "launcher", "Preset launcher"), "Preset launcher"),
            missing_hint=_optional_json_text(data, "missing_hint", "Preset missing_hint"),
            notes=_optional_json_text(data, "notes", "Preset notes"),
            steam_shortcut_name=_optional_json_text(data, "steam_shortcut_name", "Preset steam_shortcut_name"),
            launch_options=_optional_json_text(data, "launch_options", "Preset launch_options"),
        )


@dataclasses.dataclass(frozen=True)
class PresetManifest:
    generated_at: str
    root: Path
    engine: EngineSpec
    iwad_directory: Path
    pwad_directory: Path
    mod_directories: Mapping[str, Path]
    presets: tuple[Preset, ...]
    schema: str = PRESET_MANIFEST_SCHEMA
    warning: str = PRESET_MANIFEST_WARNING
    content_groups: Mapping[str, object] | None = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "schema", _required_text(self.schema, "Preset manifest schema"))
        object.__setattr__(self, "generated_at", _required_text(self.generated_at, "Preset manifest generated_at"))
        object.__setattr__(self, "root", _required_path(self.root, "Preset manifest root"))
        object.__setattr__(self, "iwad_directory", _required_path(self.iwad_directory, "IWAD directory"))
        object.__setattr__(self, "pwad_directory", _required_path(self.pwad_directory, "PWAD directory"))
        object.__setattr__(
            self,
            "mod_directories",
            {str(name): _required_path(path, f"Mod directory {name}") for name, path in self.mod_directories.items()},
        )
        object.__setattr__(self, "presets", tuple(self.presets))

    def with_content_groups(self, content_groups: Mapping[str, object]) -> "PresetManifest":
        return dataclasses.replace(self, content_groups=content_groups)

    def as_json_object(self) -> dict[str, object]:
        data: dict[str, object] = {
            "schema": self.schema,
            "generated_at": self.generated_at,
            "warning": self.warning,
            "root": str(self.root),
            "engine": self.engine.as_json_object(),
            "iwad_directory": str(self.iwad_directory),
            "pwad_directory": str(self.pwad_directory),
            "mod_directories": {name: str(path) for name, path in self.mod_directories.items()},
            "presets": [preset.as_json_object() for preset in self.presets],
        }
        if self.content_groups is not None:
            data["content_groups"] = self.content_groups
        return data

    @classmethod
    def from_json_object(cls, value: object) -> "PresetManifest":
        data = _json_object(value, "Preset manifest")
        schema = _json_text(_required_value(data, "schema", "Preset manifest schema"), "Preset manifest schema")
        if schema != PRESET_MANIFEST_SCHEMA:
            raise DoomDeckError(f"Unsupported preset manifest schema: {schema}")

        mod_directories_value = _json_object(
            _required_value(data, "mod_directories", "Preset manifest mod_directories"),
            "Preset manifest mod_directories",
        )
        presets_value = _required_value(data, "presets", "Preset manifest presets")
        if not isinstance(presets_value, list):
            raise DoomDeckError("Preset manifest presets must be a list")

        content_groups: Mapping[str, object] | None = None
        if "content_groups" in data:
            content_groups = _json_object(data["content_groups"], "Preset manifest content_groups")

        return cls(
            schema=schema,
            generated_at=_json_text(_required_value(data, "generated_at", "Preset manifest generated_at"), "Preset manifest generated_at"),
            warning=_optional_json_text(data, "warning", "Preset manifest warning") or PRESET_MANIFEST_WARNING,
            root=_json_path(_required_value(data, "root", "Preset manifest root"), "Preset manifest root"),
            engine=EngineSpec.from_json_object(_required_value(data, "engine", "Preset manifest engine")),
            iwad_directory=_json_path(_required_value(data, "iwad_directory", "IWAD directory"), "IWAD directory"),
            pwad_directory=_json_path(_required_value(data, "pwad_directory", "PWAD directory"), "PWAD directory"),
            mod_directories={
                name: _json_path(path, f"Mod directory {name}")
                for name, path in mod_directories_value.items()
            },
            presets=tuple(Preset.from_json_object(preset) for preset in presets_value),
            content_groups=content_groups,
        )
