"""Build DoomDeck's source-port and Steam Input control profiles."""
from __future__ import annotations

from doomdeck.domain.control_mapping import (
    ControlAction,
    ControlProfile,
    ControlScheme,
    ControlSchemeAlternative,
    KeyboardMouseOutput,
    PhysicalInput,
    SensitivitySettings,
    SourcePortAlias,
    SourcePortBinding,
    SourcePortControlProfile,
    SteamInputBinding,
)

DOOMDECK_STEAM_INPUT_TITLE = "DoomDeck Hybrid KB/M"
DOOMDECK_STEAM_INPUT_DESCRIPTION = (
    "Steam Deck layout generated by DoomDeck for Doom Runner and UZDoom-family presets. "
    "It emits keyboard/mouse inputs, uses no gyro, and keeps quick load behind a long-press rear grip."
)
QUICKLOAD_LONG_PRESS_MS = 1500


def key(value: str, label: str) -> KeyboardMouseOutput:
    return KeyboardMouseOutput("key", value, label)


def mouse_button(value: str, label: str) -> KeyboardMouseOutput:
    return KeyboardMouseOutput("mouse_button", value, label)


def mouse_wheel(value: str, label: str) -> KeyboardMouseOutput:
    return KeyboardMouseOutput("mouse_wheel", value, label)


def build_default_control_scheme() -> ControlScheme:
    """Return the selected Steam Deck keyboard/mouse layout."""

    bindings = (
        SteamInputBinding(PhysicalInput.LEFT_STICK, ControlAction.MOVE, key("WASD", "Move")),
        SteamInputBinding(PhysicalInput.RIGHT_TRACKPAD, ControlAction.AIM, KeyboardMouseOutput("mouse", "absolute_mouse", "Aim"), "Soft_Press"),
        SteamInputBinding(PhysicalInput.RIGHT_STICK, ControlAction.AIM, KeyboardMouseOutput("mouse", "joystick_mouse", "Coarse aim")),
        SteamInputBinding(PhysicalInput.RIGHT_TRIGGER, ControlAction.FIRE, mouse_button("LEFT", "Fire")),
        SteamInputBinding(PhysicalInput.LEFT_TRIGGER, ControlAction.ALT_FIRE, mouse_button("RIGHT", "Alt fire / aim down sights")),
        SteamInputBinding(PhysicalInput.LEFT_BUMPER, ControlAction.PREVIOUS_WEAPON, mouse_wheel("SCROLL_DOWN", "Previous weapon")),
        SteamInputBinding(PhysicalInput.RIGHT_BUMPER, ControlAction.NEXT_WEAPON, mouse_wheel("SCROLL_UP", "Next weapon")),
        SteamInputBinding(PhysicalInput.A, ControlAction.USE, key("E", "Use / confirm")),
        SteamInputBinding(PhysicalInput.B, ControlAction.CROUCH, key("LEFT_CONTROL", "Crouch / back")),
        SteamInputBinding(PhysicalInput.X, ControlAction.RELOAD, key("R", "Reload")),
        SteamInputBinding(PhysicalInput.Y, ControlAction.JUMP, key("SPACE", "Jump / use")),
        SteamInputBinding(PhysicalInput.DPAD, ControlAction.MENU_NAVIGATION, key("ARROW_KEYS", "Menu navigation")),
        SteamInputBinding(PhysicalInput.MENU, ControlAction.MENU, key("ESCAPE", "Menu / pause")),
        SteamInputBinding(PhysicalInput.VIEW, ControlAction.AUTOMAP, key("TAB", "Automap")),
        SteamInputBinding(PhysicalInput.L4, ControlAction.JUMP, key("SPACE", "Jump without leaving aim")),
        SteamInputBinding(PhysicalInput.R4, ControlAction.CROUCH, key("LEFT_CONTROL", "Crouch without leaving aim")),
        SteamInputBinding(PhysicalInput.L5, ControlAction.QUICK_SAVE, key("F6", "Quick save")),
        SteamInputBinding(
            PhysicalInput.R5,
            ControlAction.QUICK_LOAD,
            key("F9", "Quick load"),
            activation="Long_Press",
            long_press_ms=QUICKLOAD_LONG_PRESS_MS,
            note="Long press only; no base-layer F9 binding is emitted.",
        ),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.DIRECT_WEAPON, KeyboardMouseOutput("radial_menu", "1-9,0", "Weapon wheel")),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.MOD_ACTION, key("Q", "Kick / mod action"), layer="radial"),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.FLASHLIGHT_OR_ZOOM, key("F", "Flashlight / zoom / mod utility"), layer="radial"),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.MOD_ACTION, key("G", "Project Brutality equipment"), layer="radial"),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.MOD_ACTION, key("U", "Project Brutality unload"), layer="radial"),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.MOD_ACTION, key("LEFT_ALT", "Project Brutality dash"), layer="radial"),
        SteamInputBinding(PhysicalInput.LEFT_TRACKPAD, ControlAction.MOD_ACTION, key("L", "Project Brutality clear debris"), layer="radial"),
    )
    return ControlScheme(
        name=DOOMDECK_STEAM_INPUT_TITLE,
        description=DOOMDECK_STEAM_INPUT_DESCRIPTION,
        bindings=bindings,
        sensitivity=SensitivitySettings(),
        alternatives=(
            ControlSchemeAlternative(
                "Console-like face buttons",
                "ABXY carries use/crouch/reload/jump with bumpers for weapon cycling.",
                "Comfortable and familiar, but jump/reload/use pull the right thumb off aim when gyro is disabled.",
            ),
            ControlSchemeAlternative(
                "PC-preserving combat layout",
                "Right trackpad/stick emit mouse, left stick emits WASD, and rear grips keep movement actions under fingers.",
                "Best combat feel, but needs a radial menu and a documented menu/utility plan.",
            ),
            ControlSchemeAlternative(
                "Safety/menu-first layout",
                "D-pad and face buttons prioritize launcher/menu navigation and move save/load to utility chords.",
                "Great for Doom Runner setup screens, but weaker during normal combat and weapon switching.",
            ),
        ),
        evidence=(
            "id Software DOOM m_misc.c defaults: Space use, Right Ctrl fire, Shift run/speed.",
            "GZDoom commonbinds/defbinds: WASD, E use, Mouse1 fire, Mouse2 alt-fire, wheel weapons, F6/F9 save/load.",
            "UZDoom defaults: Ctrl crouch, R reload, Mouse3 zoom, controller triggers/bumpers, rear paddles for secondary actions.",
            "Brutal Doom FAQ/ModDB: Right Mouse alt-fire/ADS, Q kick, WASD/E/Space/Ctrl conventions.",
            "Project Brutality KEYCONF: Q kick, F quick melee, G equipment, U unload, LeftAlt dash, L clear debris.",
            "Valve Steam Deck/Steam Input docs: keyboard/mouse outputs, trackpad mouse modes, action/chord style layouts, four grip buttons.",
        ),
        rationale=(
            "Hybrid PC-preserving controls best satisfy keyboard/mouse Steam Input, no gyro, and modern console Doom ergonomics: "
            "aim stays on the right trackpad/stick, triggers fire, bumpers cycle weapons, face buttons remain familiar, "
            "and rear grips cover jump/crouch/quicksave/long-press quickload."
        ),
        gyro_enabled=False,
    )


def build_uzdoom_control_profiles() -> tuple[SourcePortControlProfile, ...]:
    return (
        build_uzdoom_control_profile(ControlProfile.CLASSIC),
        build_uzdoom_control_profile(ControlProfile.MODERN),
        build_uzdoom_control_profile(ControlProfile.BRUTAL_DOOM),
        build_uzdoom_control_profile(ControlProfile.PROJECT_BRUTALITY),
    )


def build_uzdoom_control_profile(profile: ControlProfile) -> SourcePortControlProfile:
    if profile == ControlProfile.CLASSIC:
        return _classic_profile()
    if profile == ControlProfile.MODERN:
        return _modern_profile(ControlProfile.MODERN, "Modern dual-stick/FPS-style behavior for UZDoom.", bind_q=True, bind_f=True)
    if profile == ControlProfile.BRUTAL_DOOM:
        return _modern_profile(
            ControlProfile.BRUTAL_DOOM,
            "Brutal Doom behavior; preserves Q for the mod's default kick binding.",
            bind_q=False,
            bind_f=True,
        )
    return _modern_profile(
        ControlProfile.PROJECT_BRUTALITY,
        "Project Brutality behavior; preserves mod KEYCONF defaults for Q/F/G/U/Alt/L utilities.",
        bind_q=False,
        bind_f=False,
    )


def _common_aliases(*, crouch_back: bool) -> tuple[SourcePortAlias, ...]:
    aliases = [
        SourcePortAlias("+deck_use_select", '"+use; menu_select"'),
        SourcePortAlias("-deck_use_select", '"-use"'),
    ]
    if crouch_back:
        aliases.extend(
            [
                SourcePortAlias("+deck_crouch_back", '"+crouch; menu_back"'),
                SourcePortAlias("-deck_crouch_back", '"-crouch"'),
            ]
        )
    else:
        aliases.extend(
            [
                SourcePortAlias("+deck_menu_back", '"menu_back"'),
                SourcePortAlias("-deck_menu_back", '""'),
            ]
        )
    return tuple(aliases)


def _base_bindings() -> list[SourcePortBinding]:
    return [
        SourcePortBinding("w", "+forward"),
        SourcePortBinding("s", "+back"),
        SourcePortBinding("a", "+moveleft"),
        SourcePortBinding("d", "+moveright"),
        SourcePortBinding("uparrow", "menu_up"),
        SourcePortBinding("downarrow", "menu_down"),
        SourcePortBinding("leftarrow", "menu_left"),
        SourcePortBinding("rightarrow", "menu_right"),
        SourcePortBinding("mouse1", "+attack"),
        SourcePortBinding("mouse2", "+altattack"),
        SourcePortBinding("e", "+deck_use_select"),
        SourcePortBinding("capslock", '"toggle cl_run"'),
        SourcePortBinding("tab", "togglemap"),
        SourcePortBinding("F6", "quicksave"),
        SourcePortBinding("F9", "quickload"),
        SourcePortBinding("escape", "menu_main"),
        SourcePortBinding("enter", "menu_select"),
        SourcePortBinding("backspace", "menu_back"),
        SourcePortBinding("mwheelup", "weapnext"),
        SourcePortBinding("mwheeldown", "weapprev"),
    ]


def _weapon_slot_bindings() -> list[SourcePortBinding]:
    return [*(SourcePortBinding(str(slot), f"slot {slot}") for slot in range(1, 10)), SourcePortBinding("0", "slot 0")]


def _classic_profile() -> SourcePortControlProfile:
    bindings = _base_bindings()
    bindings.extend(
        [
            SourcePortBinding("space", "+deck_use_select"),
            SourcePortBinding("leftctrl", "+deck_menu_back"),
            SourcePortBinding("RTrigger", "+attack"),
            SourcePortBinding("LTrigger", "+altattack"),
            SourcePortBinding("LShoulder", "weapprev"),
            SourcePortBinding("RShoulder", "weapnext"),
            SourcePortBinding("Pad_A", "+deck_use_select"),
            SourcePortBinding("Pad_B", "menu_back"),
            SourcePortBinding("Pad_Start", "menu_main"),
            SourcePortBinding("Pad_Back", "+showscores"),
        ]
    )
    bindings.extend(_weapon_slot_bindings())
    return SourcePortControlProfile(
        profile=ControlProfile.CLASSIC,
        description="Classic-style Doom behavior for UZDoom/GZDoom-family source ports.",
        cvars=(
            ("freelook", "false"),
            ("lookstrafe", "false"),
            ("m_pitch", "0"),
            ("sv_allowjump", "false"),
            ("sv_allowcrouch", "false"),
            ("cl_run", "true"),
            ("crosshair", "0"),
        ),
        aliases=_common_aliases(crouch_back=False),
        bindings=tuple(bindings),
    )


def _modern_profile(profile: ControlProfile, description: str, *, bind_q: bool, bind_f: bool) -> SourcePortControlProfile:
    bindings = _base_bindings()
    bindings.extend(
        [
            SourcePortBinding("space", "+jump"),
            SourcePortBinding("leftctrl", "+deck_crouch_back"),
            SourcePortBinding("c", "+crouch"),
            SourcePortBinding("r", "+reload"),
            SourcePortBinding("Pad_A", "+deck_use_select"),
            SourcePortBinding("Pad_B", "+deck_crouch_back"),
            SourcePortBinding("Pad_X", "+reload"),
            SourcePortBinding("Pad_Y", "+jump"),
            SourcePortBinding("Pad_Start", "menu_main"),
            SourcePortBinding("Pad_Back", "+showscores"),
            SourcePortBinding("RTrigger", "+attack"),
            SourcePortBinding("LTrigger", "+altattack"),
            SourcePortBinding("LShoulder", "weapprev"),
            SourcePortBinding("RShoulder", "weapnext"),
        ]
    )
    if bind_q:
        bindings.append(SourcePortBinding("q", "weapprev"))
    if bind_f:
        bindings.append(SourcePortBinding("f", "+zoom"))
    bindings.extend(_weapon_slot_bindings())
    return SourcePortControlProfile(
        profile=profile,
        description=description,
        cvars=(
            ("freelook", "true"),
            ("lookstrafe", "false"),
            ("m_pitch", "1"),
            ("sv_allowjump", "true"),
            ("sv_allowcrouch", "true"),
            ("cl_run", "true"),
            ("crosshair", "1"),
        ),
        aliases=_common_aliases(crouch_back=True),
        bindings=tuple(bindings),
    )
