"""Generate DoomDeck user-facing setup documentation."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Optional

from doomdeck.application.doomrunner import doomrunner_options_paths
from doomdeck.application.proton import proton_windows_path
from doomdeck.domain.deck import STEAM_DECK_HEIGHT, STEAM_DECK_TARGET_FPS, STEAM_DECK_WIDTH
from doomdeck.domain.models import Dirs
from doomdeck.domain.mods import PROJECT_BRUTALITY_MOD
from doomdeck.infrastructure.files import atomic_write_text


def render_content_group_guide(manifest: dict[str, Any]) -> str:
    content_groups = manifest.get("content_groups", {})
    if not isinstance(content_groups, dict):
        return ""
    section_titles = {
        "presets": "Preset Groups",
        "map_packs": "Map Pack Groups",
        "mods": "Mod Groups",
    }
    output = "\n## Automatic Content Groups\n\nDoomDeck writes group metadata separately from launchable items. Group headings are labels only; the entries listed under them remain the selectable presets, WADs, map packs, and mods.\n"
    wrote_any = False
    for section_key, title in section_titles.items():
        groups = content_groups.get(section_key, [])
        if not isinstance(groups, list) or not groups:
            continue
        wrote_any = True
        output += f"\n### {title}\n"
        for group in groups:
            if not isinstance(group, dict):
                continue
            output += f"\n#### {group.get('display_name', group.get('id', 'Group'))}\n"
            items = group.get("items", [])
            if not isinstance(items, list):
                continue
            for item in items:
                if not isinstance(item, dict):
                    continue
                path = f" - `{item['path']}`" if item.get("path") else ""
                output += f"- `{item.get('display_name', item.get('id', 'item'))}`{path}\n"
    return output if wrote_any else ""


def write_docs(
    dirs: Dirs,
    manifest: dict[str, Any],
    brutal_path: Optional[Path],
    project_brutality_path: Optional[Path],
    dry_run: bool,
    logger: logging.Logger,
    *,
    appid: str,
    brutal_doom_source_url: str,
    project_brutality_repo: str,
) -> None:
    # Generated Markdown, not a SQL expression.
    layout = (  # nosec B608
        f"""# Doom Deck Setup Layout

Generated by `doomdeck`.

```text
{dirs.root}/
├── tools/doomrunner/              Windows Doom Runner executable for Proton
├── source-ports/uzdoom/           Windows UZDoom executable for Proton
├── iwads/                         Legal IWAD copies from Steam app {appid}
├── pwads/                         User PWADs and map packs
├── mods/brutal-doom/              Managed Brutal Doom .pk3 and update metadata
├── mods/project-brutality/         Downloaded Project Brutality .pk3
├── configs/doomrunner/            Generated manifest and Doom Runner setup guide
├── configs/uzdoom/                Classic and modern UZDoom config templates
├── launchers/                     Generated preset helper scripts and launch metadata
├── saves/                         Save-game location for future use
├── screenshots/                   Screenshot location for future use
├── downloads/                     Downloaded upstream release assets
├── backups/                       Backups made before replacement/modification
└── logs/                          Script logs
```
"""
    )
    steam_input = f"""# Steam Input Profiles for Doom Runner / UZDoom

DoomDeck installs the Windows builds of Doom Runner and UZDoom and forces the generated Doom Runner Steam shortcut to use the configured Steam compatibility tool. The default is `proton_10`. Steam Input should present Steam Deck, Xbox, PlayStation, and other supported controllers to Windows UZDoom as a gamepad.

The generated UZDoom configs enable joystick input and bind common Steam Deck gamepad buttons directly. Steam's standard Gamepad layout should work for the generated presets; use Steam's controller configurator only if you want a custom layout.

The generated UZDoom configs also default to fullscreen {STEAM_DECK_WIDTH}x{STEAM_DECK_HEIGHT}, vsync on, and a {STEAM_DECK_TARGET_FPS} FPS cap.

For Steam Deck rear buttons, set Steam Input so L4 sends `F6` and R4 sends `F9`. DoomDeck binds `F6` to UZDoom quick save and `F9` to UZDoom quick load in both generated profiles.

## Classic Doom controls

Recommended Steam Deck layout for the `Vanilla Doom` preset:

- Left stick: movement.
- Right stick or right trackpad: horizontal turn only, low-to-moderate sensitivity.
- Right trigger: attack.
- A: use in-game and select in menus.
- B: back in menus.
- Left/right bumpers: weapon cycling.
- Menu/Start: open menu.
- L4: quick save, through a Steam Input `F6` mapping.
- R4: quick load, through a Steam Input `F9` mapping.
- Disable gyro and vertical mouse if you want a stricter classic feel.

The generated `configs/uzdoom/classic/autoexec.cfg` sets `freelook false`, `sv_allowjump false`, and `sv_allowcrouch false`.

## Modern Doom / Brutal Doom / Project Brutality controls

Recommended Steam Deck layout for the `UZDoom`, `Brutal Doom`, and `Project Brutality` presets:

- Left stick: movement.
- Right stick: mouse look or joystick look, conservative sensitivity.
- Right trigger: primary fire.
- Left trigger: secondary fire or alt-fire.
- A: use in-game and select in menus.
- B: crouch in-game and back in menus.
- X: reload.
- Y: jump.
- Bumpers: weapon cycle.
- Menu/Start: open menu.
- L4: quick save, through a Steam Input `F6` mapping.
- R4: quick load, through a Steam Input `F9` mapping.
- Optional gyro: mouse as gyro, active on right-stick touch or left trigger.

The generated `configs/uzdoom/modern/autoexec.cfg` enables freelook, jump, crouch, reload, alt-fire, quick save, and quick load bindings.
"""
    live_options_primary = doomrunner_options_paths(dirs)[0]
    doomrunner_guide = f"""# Doom Runner Setup Guide

DoomDeck installs the Windows builds of Doom Runner and UZDoom, copies Steam IWADs, creates one Doom Runner Steam shortcut that runs through Proton, writes Doom Runner's generated options file, and writes a stable preset manifest:

`{live_options_primary}`

`{dirs.doomrunner_config / 'preset-manifest.json'}`

DoomDeck also writes a Doom Runner options copy into the generated Steam shortcut's Proton prefix when Steam shortcut creation is enabled. All generated presets are launched from inside Doom Runner.

Doom Runner should open through Steam/Proton with the generated UZDoom engine, IWADs, and presets already listed. Existing generated Doom Runner options are backed up under:

`{dirs.backups}`

## Initial Doom Runner check

1. Launch `Doom Runner` from Steam Gaming Mode.

2. Confirm this engine exists:

   - Engine name: `UZDoom`
   - Executable path: `{proton_windows_path(dirs.uzdoom / 'uzdoom.exe')}`
   - Engine family: `UZDoom` if shown, otherwise `ZDoom` / `GZDoom-family`
   - Config directory: `{proton_windows_path(dirs.uzdoom_config)}`
   - Data directory: `{proton_windows_path(dirs.root)}`

3. Confirm IWADs are listed from:

   `{dirs.iwads}`

4. Confirm the map directory is:

   `{dirs.pwads}`

   ModDB WAD archives installed with `doomdeck install-wads` are extracted here so they can be selected inside a preset.

5. Confirm these presets are listed:

"""
    for preset in manifest.get("presets", []):
        files = ", ".join(preset.get("files") or []) or "none"
        doomrunner_guide += f"- `{preset['name']}`\n  - IWAD: `{preset['iwad']}`\n  - Config: `{preset['config']}`\n  - Autoexec: `{preset['autoexec']}`\n  - Files/mods: `{files}`\n"
    doomrunner_guide += render_content_group_guide(manifest)
    doomrunner_guide += """
## Preset launchers

DoomDeck creates helper scripts in `launchers/` for each preset. These scripts are not added to Steam. Open the single `Doom Runner` Steam shortcut and choose a generated preset there so Windows UZDoom runs through Proton with Steam Input.
"""
    brutal = f"""# Brutal Doom

Brutal Doom is checked from the official ModDB project/download pages when you rerun:

```bash
doomdeck install
```

The default update channel is `latest`, which can include beta/test builds such as v22 test releases. To prefer the newest non-beta candidate DoomDeck can identify, use:

```bash
doomdeck install --brutal-doom-channel stable
```

Managed file:

`{brutal_path or 'not found yet'}`

Metadata:

`{dirs.brutal / 'brutal-doom.json'}`

To use a specific browser-downloaded file instead:

```bash
doomdeck install --brutal-doom-file /path/to/brutal-doom.pk3
```

To skip Brutal Doom update checks:

```bash
doomdeck install --skip-brutal-doom
```

Source project:

`{brutal_doom_source_url}`
"""
    project_brutality = f"""# Project Brutality

Project Brutality is checked from GitHub and installed as a root-normalized `.pk3` for UZDoom/Doom Runner.

Managed file:

`{project_brutality_path or (dirs.project_brutality / PROJECT_BRUTALITY_MOD.alias)}`

To update it, rerun:

```bash
doomdeck install
```

To use a manually downloaded file instead:

```bash
doomdeck install --project-brutality-file /path/to/Project_Brutality.pk3
```

Source repository:

`https://github.com/{project_brutality_repo}`
"""
    atomic_write_text(dirs.docs / "DIRECTORY_LAYOUT.md", layout, dry_run, logger)
    atomic_write_text(dirs.docs / "STEAM_INPUT_PROFILES.md", steam_input, dry_run, logger)
    atomic_write_text(dirs.docs / "DOOM_RUNNER_SETUP.md", doomrunner_guide, dry_run, logger)
    atomic_write_text(dirs.brutal / "README.md", brutal, dry_run, logger)
    atomic_write_text(dirs.project_brutality / "README.md", project_brutality, dry_run, logger)
