"""Build DoomDeck preset manifests from managed domain state."""
from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any, Optional

from doomdeck.domain.models import Dirs
from doomdeck.domain.mods import BRUTAL_DOOM_MOD, PROJECT_BRUTALITY_MOD
from doomdeck.domain.wads import DEFAULT_PRESET_IWADS, iwad_dest_name


def choose_default_preset_iwad(dirs: Dirs) -> Optional[Path]:
    for iwad_name in DEFAULT_PRESET_IWADS:
        iwad_path = dirs.iwads / iwad_dest_name(iwad_name)
        if iwad_path.exists():
            return iwad_path
    return None


def build_preset_manifest(dirs: Dirs, brutal_path: Optional[Path], project_brutality_path: Optional[Path]) -> dict[str, Any]:
    presets: list[dict[str, Any]] = []
    default_iwad = choose_default_preset_iwad(dirs)
    if default_iwad:
        presets.extend(
            [
                {
                    "name": "Vanilla Doom",
                    "category": "Vanilla",
                    "engine": "UZDoom",
                    "iwad": str(default_iwad),
                    "files": [],
                    "config": str(dirs.uzdoom_config / "classic" / "uzdoom.ini"),
                    "autoexec": str(dirs.uzdoom_config / "classic" / "autoexec.cfg"),
                    "launcher": str(dirs.launchers / "Vanilla_Doom.sh"),
                    "notes": "Classic-style UZDoom launch. Change the selected IWAD in Doom Runner to switch Doom, Doom II, TNT, or Plutonia.",
                },
                {
                    "name": "UZDoom",
                    "category": "UZDoom",
                    "engine": "UZDoom",
                    "iwad": str(default_iwad),
                    "files": [],
                    "config": str(dirs.uzdoom_config / "modern" / "uzdoom.ini"),
                    "autoexec": str(dirs.uzdoom_config / "modern" / "autoexec.cfg"),
                    "launcher": str(dirs.launchers / "UZDoom.sh"),
                    "notes": "UZDoom without gameplay mods. Change the selected IWAD in Doom Runner to switch base games.",
                },
                {
                    "name": BRUTAL_DOOM_MOD.name,
                    "category": BRUTAL_DOOM_MOD.name,
                    "engine": "UZDoom",
                    "iwad": str(default_iwad),
                    "files": [str(brutal_path or BRUTAL_DOOM_MOD.alias_path(dirs.brutal))],
                    "config": str(dirs.uzdoom_config / "modern" / "uzdoom.ini"),
                    "autoexec": str(dirs.uzdoom_config / "modern" / "autoexec.cfg"),
                    "launcher": str(dirs.launchers / "Brutal_Doom.sh"),
                    "missing_hint": "Rerun install to check ModDB, or use --brutal-doom-file/--brutal-doom-url.",
                    "notes": f"Requires mods/brutal-doom/{BRUTAL_DOOM_MOD.alias}. Change the selected IWAD in Doom Runner to switch base games.",
                },
                {
                    "name": PROJECT_BRUTALITY_MOD.name,
                    "category": PROJECT_BRUTALITY_MOD.name,
                    "engine": "UZDoom",
                    "iwad": str(default_iwad),
                    "files": [str(project_brutality_path or PROJECT_BRUTALITY_MOD.alias_path(dirs.project_brutality))],
                    "config": str(dirs.uzdoom_config / "modern" / "uzdoom.ini"),
                    "autoexec": str(dirs.uzdoom_config / "modern" / "autoexec.cfg"),
                    "launcher": str(dirs.launchers / "Project_Brutality.sh"),
                    "missing_hint": "Rerun install to download Project Brutality, or use --project-brutality-file /path/to/Project_Brutality.pk3.",
                    "notes": "Downloads Project Brutality from GitHub and installs it as mods/project-brutality/project-brutality.pk3.",
                },
            ]
        )
    return {
        "schema": "doom-deck-setup/preset-manifest/v1",
        "generated_at": _dt.datetime.now().isoformat(timespec="seconds"),
        "warning": "This is a stable manifest generated by DoomDeck. Doom Runner's live options.json is generated separately.",
        "root": str(dirs.root),
        "engine": {
            "name": "UZDoom",
            "executable": str(dirs.uzdoom / "uzdoom.sh"),
            "family": "UZDoom/ZDoom",
            "config_directory": str(dirs.uzdoom_config),
            "data_directory": str(dirs.root),
        },
        "iwad_directory": str(dirs.iwads),
        "pwad_directory": str(dirs.pwads),
        "mod_directories": {
            "brutal_doom": str(dirs.brutal),
            "project_brutality": str(dirs.project_brutality),
        },
        "presets": presets,
    }
