"""Generate UZDoom configuration profiles for Steam Deck controls."""
from __future__ import annotations

import logging

from doomdeck.domain.deck import STEAM_DECK_HEIGHT, STEAM_DECK_TARGET_FPS, STEAM_DECK_WIDTH
from doomdeck.domain.models import Dirs
from doomdeck.infrastructure.files import atomic_write_text

UZDOOM_STEAM_DECK_GLOBAL_SETTINGS = [
    ("vid_fullscreen", "true"),
    ("vid_defwidth", str(STEAM_DECK_WIDTH)),
    ("vid_defheight", str(STEAM_DECK_HEIGHT)),
    ("vid_aspect", "0"),
    ("vid_cropaspect", "false"),
    ("vid_vsync", "true"),
    ("vid_maxfps", str(STEAM_DECK_TARGET_FPS)),
    ("vid_preferbackend", "1"),
    ("vid_rendermode", "4"),
    ("vk_exclusivefullscreen", "false"),
    ("autoloadwidescreen", "true"),
    ("gl_fxaa", "0"),
    ("gl_multisample", "1"),
    ("gl_ssao", "0"),
    ("gl_light_shadowmap", "false"),
    ("gl_texture_filter", "0"),
    ("gl_texture_filter_anisotropic", "4"),
    ("vid_scale_linear", "false"),
    ("vid_scalefactor", "1"),
    ("vid_scalemode", "0"),
    ("m_blockcontrollers", "false"),
    ("use_joystick", "true"),
]


def build_uzdoom_ini() -> str:
    lines = ["; Generated by doomdeck", "[GlobalSettings]"]
    lines.extend(f"{key}={value}" for key, value in UZDOOM_STEAM_DECK_GLOBAL_SETTINGS)
    lines.append("")
    return "\n".join(lines)


def build_uzdoom_deck_autoexec_settings() -> str:
    return "\n".join(f"{key} {value}" for key, value in UZDOOM_STEAM_DECK_GLOBAL_SETTINGS)


def write_uzdoom_configs(dirs: Dirs, dry_run: bool, logger: logging.Logger) -> None:
    deck_settings = build_uzdoom_deck_autoexec_settings()
    classic_cfg = f"""// Generated by doomdeck
// Classic-style Doom behavior for UZDoom/GZDoom-family source ports.
// Steam Deck display, graphics, and gamepad defaults.

{deck_settings}

freelook false
lookstrafe false
m_pitch 0
sv_allowjump false
sv_allowcrouch false
cl_run true
crosshair 0

alias +deck_use_select "+use; menu_select"
alias -deck_use_select "-use"

bind w +forward
bind s +back
bind a +moveleft
bind d +moveright
bind leftarrow +left
bind rightarrow +right
bind mouse1 +attack
bind e +use
bind space +use
bind tab +showscores
bind F6 quicksave
bind F9 quickload
bind escape menu_main
bind enter menu_select
bind backspace menu_back
bind Pad_A +deck_use_select
bind Pad_B menu_back
bind Pad_Start menu_main
bind Pad_Back pause
bind Pad_LThumb quicksave
bind Pad_RThumb quickload
bind RTrigger +attack
bind LShoulder weapprev
bind RShoulder weapnext
bind mwheelup weapnext
bind mwheeldown weapprev
bind 1 slot 1
bind 2 slot 2
bind 3 slot 3
bind 4 slot 4
bind 5 slot 5
bind 6 slot 6
bind 7 slot 7
"""
    modern_cfg = f"""// Generated by doomdeck
// Modern dual-stick/FPS-style behavior for UZDoom, Brutal Doom, and Project Brutality.
// Steam Deck display, graphics, and gamepad defaults.

{deck_settings}

freelook true
lookstrafe false
m_pitch 1
sv_allowjump true
sv_allowcrouch true
cl_run true
crosshair 1

alias +deck_use_select "+use; menu_select"
alias -deck_use_select "-use"
alias +deck_crouch_back "+crouch; menu_back"
alias -deck_crouch_back "-crouch"

bind w +forward
bind s +back
bind a +moveleft
bind d +moveright
bind mouse1 +attack
bind mouse2 +altattack
bind e +use
bind space +jump
bind leftctrl +crouch
bind c +crouch
bind r +reload
bind q weapprev
bind mwheelup weapnext
bind mwheeldown weapprev
bind f +zoom
bind tab +showscores
bind F6 quicksave
bind F9 quickload
bind escape menu_main
bind enter menu_select
bind backspace menu_back
bind Pad_A +deck_use_select
bind Pad_B +deck_crouch_back
bind Pad_X +reload
bind Pad_Y +jump
bind Pad_Start menu_main
bind Pad_Back pause
bind Pad_LThumb quicksave
bind Pad_RThumb quickload
bind RTrigger +attack
bind LTrigger +altattack
bind LShoulder weapprev
bind RShoulder weapnext
bind 1 slot 1
bind 2 slot 2
bind 3 slot 3
bind 4 slot 4
bind 5 slot 5
bind 6 slot 6
bind 7 slot 7
"""
    classic_ini = build_uzdoom_ini()
    modern_ini = build_uzdoom_ini()
    atomic_write_text(dirs.uzdoom_config / "classic" / "autoexec.cfg", classic_cfg, dry_run, logger)
    atomic_write_text(dirs.uzdoom_config / "modern" / "autoexec.cfg", modern_cfg, dry_run, logger)
    atomic_write_text(dirs.uzdoom_config / "classic" / "uzdoom.ini", classic_ini, dry_run, logger)
    atomic_write_text(dirs.uzdoom_config / "modern" / "uzdoom.ini", modern_ini, dry_run, logger)
